media-video/pipewire sound-server
media-video/wireplumber
media-libs/mesa vulkan vaapi vdpau
kde-plasma/plasma-meta
x11-misc/sddm
sys-libs/minizip-ng compat
x11-libs/libdrm video_cards_radeon
dev-qt/qtbase cups
