# AMD RDNA2 GPU stack & firmware
media-libs/mesa ~amd64
x11-libs/libdrm ~amd64
sys-kernel/linux-firmware ~amd64
dev-util/vulkan-tools ~amd64
media-video/libva-utils ~amd64
sys-process/nvtop ~amd64
dev-util/vulkan-headers ~amd64
dev-util/glslang ~amd64
dev-util/spirv-tools ~amd64
dev-util/spirv-headers ~amd64
dev-util/vulkan-* ~amd64
media-libs/vulkan-* ~amd64
