# KDE Plasma, Frameworks, Apps, Wayland & Qt6
kde-plasma/* ~amd64
kde-frameworks/* ~amd64
kde-apps/* ~amd64
dev-qt/* ~amd64
x11-misc/sddm ~amd64
dev-libs/wayland ~amd64
dev-libs/wayland-protocols ~amd64
gui-libs/* ~amd64
media-libs/kquickimageeditor ~amd64
gui-apps/* ~amd64
dev-util/wayland-scanner ~amd64
media-gfx/kio-ps-thumbnailer ~amd64
