# Audio engine & Media codecs
media-video/pipewire ~amd64
media-video/wireplumber ~amd64
media-video/ffmpeg ~amd64
media-video/ffmpegthumbnailer ~amd64
media-video/mpv ~amd64
media-libs/dav1d ~amd64
media-libs/svt-av1 ~amd64
media-libs/libsdl3 ~amd64
net-misc/yt-dlp ~amd64
