# Modern CLI utilities, Linker & Editors
app-shells/fzf ~amd64
app-shells/zoxide ~amd64
sys-apps/bat ~amd64
sys-apps/eza ~amd64
sys-apps/fd ~amd64
sys-apps/ripgrep ~amd64
sys-fs/duf ~amd64
app-misc/fastfetch ~amd64
app-editors/neovim ~amd64
sys-process/btop ~amd64
sys-devel/mold ~amd64
dev-lua/* ~amd64
dev-libs/tree-sitter* ~amd64
