# Compute & OpenCL
dev-libs/rocm-opencl-runtime ~amd64
dev-libs/opencl-icd-loader ~amd64
virtual/opencl ~amd64
llvm-runtimes/libclc ~amd64
dev-util/spirv-llvm-translator ~amd64
llvm-core/* ~amd64
llvm-runtimes/* ~amd64
dev-libs/rocr-* ~amd64
dev-libs/rocm-* ~amd64
dev-util/hip* ~amd64
dev-build/rocm-cmake ~amd64
dev-libs/roct-* ~amd64
dev-util/opencl-* ~amd64
